import { useState } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Award, ShieldCheck, Star, Users, ArrowRight, BookOpen, UserCheck, MessageCircle } from "lucide-react";
import { toast } from "sonner";
import { useLanguage } from "@/hooks/useLanguage";
import SiteContentBlocks from "@/components/SiteContentBlocks";

const getPartnerTypes = (language: string) => [
  {
    type: language === "fr" ? "Ambassadeur" : "Ambassador",
    commission: "10% - 20%",
    desc: language === "fr"
      ? "Recommandez nos formations ou services digitaux à votre réseau. Idéal pour les étudiants, freelances et créateurs de contenu."
      : "Recommend our trainings or digital services to your network. Ideal for students, freelancers, and content creators.",
    features: language === "fr" ? [
      "Lien affilié de tracking unique",
      "Kit de visuels et bannières promotionnelles",
      "Paiements mensuels garantis par Mobile Money",
    ] : [
      "Unique affiliate tracking link",
      "Kit of visuals and promotional banners",
      "Monthly payments guaranteed by Mobile Money",
    ],
  },
  {
    type: language === "fr" ? "Conseiller Digital" : "Digital Advisor",
    commission: "15% - 25%",
    desc: language === "fr"
      ? "Qualifiez les besoins des PME locales (Douala/Yaoundé) et proposez nos services d'agence en tant que représentant officiel certifié."
      : "Qualify local SMB needs (Douala/Yaoundé) and propose our agency services as an official certified representative.",
    features: language === "fr" ? [
      "Mini-formation gratuite aux services GLN",
      "Fiche profil partenaire sur notre plateforme",
      "Scripts de prospection et brochures professionnelles",
    ] : [
      "Free mini-training on GLN services",
      "Partner profile page on our platform",
      "Prospecting scripts and professional brochures",
    ],
  },
  {
    type: language === "fr" ? "Closer Certifié" : "Certified Closer",
    commission: "20% - 35%",
    desc: language === "fr"
      ? "Prenez en main les leads chauds générés par nos publicités, organisez des rendez-vous et concluez les ventes de services."
      : "Take charge of hot leads generated by our ads, organize meetings, and close service sales.",
    features: language === "fr" ? [
      "Accès prioritaire à notre CRM de prospects",
      "Badge officiel de Closer Certifié GLN DIGITAL",
      "Coaching commercial hebdomadaire",
    ] : [
      "Priority access to our lead CRM",
      "Official Certified Closer badge from GLN DIGITAL",
      "Weekly sales coaching",
    ],
  },
];

const Partenaires = () => {
  const { language } = useLanguage();
  const [countryCode, setCountryCode] = useState("+237");
  const [phoneLocal, setPhoneLocal] = useState("");
  const [formData, setFormData] = useState({
    name: "",
    phone: "",
    city: "Douala",
    type: "Ambassadeur",
    experience: "",
  });
  const [submitted, setSubmitted] = useState(false);

  const partnerTypes = getPartnerTypes(language);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!/^[0-9\s-]{6,15}$/.test(phoneLocal.trim())) {
      toast.error(
        language === "fr"
          ? "Veuillez saisir un numéro de téléphone local valide."
          : "Please enter a valid local phone number."
      );
      return;
    }
    formData.phone = `${countryCode} ${phoneLocal.trim()}`;
    setSubmitted(true);
  };

  return (
    <div className="min-h-screen pt-24 pb-16">
      <SiteContentBlocks page="partenaires" />
      <div className="container mx-auto px-4 md:px-8 max-w-5xl">
        {/* Header */}
        <motion.div
          className="text-center mb-16"
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <span className="bg-primary/10 text-primary text-xs font-semibold px-4 py-1.5 rounded-full border border-primary/20">
            {language === "fr" ? "Programme Partenaires GLN" : "GLN Partner Program"}
          </span>
          <h1 className="font-heading text-4xl md:text-5xl font-bold mt-6 mb-4">
            {language === "fr" ? (
              <>Développez vos revenus en représentant des <span className="text-gradient-primary">solutions crédibles</span></>
            ) : (
              <>Grow your income by representing <span className="text-gradient-primary">credible solutions</span></>
            )}
          </h1>
          <p className="text-muted-foreground max-w-2xl mx-auto text-base">
            {language === "fr"
              ? "Devenez ambassadeur, conseiller ou closer officiel certifié par GLN DIGITAL et touchez des commissions attractives sur le marché camerounais."
              : "Become an official ambassador, advisor, or closer certified by GLN DIGITAL and earn attractive commissions in the Cameroonian market."}
          </p>
        </motion.div>

        {/* Partenariats Options Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">
          {partnerTypes.map((pt, idx) => (
            <motion.div
              key={pt.type}
              className="p-6 md:p-8 rounded-2xl bg-card border border-border/40 hover:border-primary/20 transition-colors flex flex-col justify-between"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: idx * 0.08 }}
            >
              <div>
                <span className="text-xs text-primary font-bold tracking-wider block mb-1">
                  {language === "fr" ? `Commission : ${pt.commission}` : `Commission: ${pt.commission}`}
                </span>
                <h3 className="font-heading text-lg font-bold mb-3">{pt.type}</h3>
                <p className="text-muted-foreground text-xs leading-relaxed mb-6">{pt.desc}</p>
                <div className="space-y-2 mb-6">
                  {pt.features.map((feat, fidx) => (
                    <div key={fidx} className="flex items-center gap-2 text-xs text-muted-foreground">
                      <ShieldCheck className="w-4 h-4 text-primary shrink-0" />
                      <span>{feat}</span>
                    </div>
                  ))}
                </div>
              </div>
              <Link
                to="/partenaires-dashboard"
                className="w-full bg-secondary hover:bg-primary/20 text-center py-2.5 rounded-lg font-semibold text-xs border border-border transition-colors block"
              >
                {language === "fr" ? "Accéder au Dashboard" : "Access Dashboard"}
              </Link>
            </motion.div>
          ))}
        </div>

        {/* Application Form */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          <div className="space-y-6">
            <h2 className="font-heading text-2xl font-bold">
              {language === "fr" ? "Pourquoi nous rejoindre ?" : "Why join us?"}
            </h2>
            <div className="space-y-4">
              <div className="flex gap-4">
                <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center shrink-0 text-primary">
                  <UserCheck className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="font-heading font-bold text-sm">
                    {language === "fr" ? "Crédibilité totale" : "Total credibility"}
                  </h4>
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    {language === "fr"
                      ? "Vous vendez des services d'une agence ayant fait ses preuves avec des clients comme Vendôme Hôtel ou Résidence HMR."
                      : "You sell the services of a proven agency with clients like Vendôme Hôtel or Résidence HMR."}
                  </p>
                </div>
              </div>
              <div className="flex gap-4">
                <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center shrink-0 text-primary">
                  <Award className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="font-heading font-bold text-sm">
                    {language === "fr" ? "Formation & Certification" : "Training & Certification"}
                  </h4>
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    {language === "fr"
                      ? "Nous vous formons aux techniques de vente et objections pour vous garantir des résultats rapides."
                      : "We train you on sales techniques and handling objections to ensure fast results."}
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div className="p-6 md:p-8 rounded-2xl bg-card border border-border/40">
            <h3 className="font-heading font-bold text-lg mb-6">
              {language === "fr" ? "Rejoindre le réseau de partenaires" : "Join the partner network"}
            </h3>
            {submitted ? (
              <div className="text-center py-8 space-y-4">
                <ShieldCheck className="w-12 h-12 text-primary mx-auto" />
                <h4 className="font-heading font-bold text-lg">
                  {language === "fr" ? "Candidature reçue !" : "Application received!"}
                </h4>
                <p className="text-xs text-muted-foreground">
                  {language === "fr"
                    ? "Nous analysons votre profil et vous contacterons sous 48 heures pour valider votre accès."
                    : "We are analyzing your profile and will contact you within 48 hours to validate your access."}
                </p>
              </div>
            ) : (
              <form onSubmit={handleSubmit} className="space-y-4">
                <div>
                  <label className="text-xs font-semibold text-muted-foreground block mb-1">
                    {language === "fr" ? "Nom complet" : "Full name"}
                  </label>
                  <input
                    type="text"
                    required
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                    className="w-full bg-secondary border border-border rounded-lg px-4 py-2.5 text-xs text-foreground focus:outline-none focus:border-primary"
                    placeholder={language === "fr" ? "Votre nom complet" : "Your full name"}
                  />
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label className="text-xs font-semibold text-muted-foreground block mb-1">
                      {language === "fr" ? "Téléphone (WhatsApp)" : "Phone (WhatsApp)"}
                    </label>
                    <div className="flex gap-2">
                      <select
                        value={countryCode}
                        onChange={(e) => setCountryCode(e.target.value)}
                        className="bg-secondary border border-border rounded-lg px-2 py-2.5 text-xs text-foreground focus:outline-none focus:border-primary"
                      >
                        <option value="+237">+237 (CM)</option>
                        <option value="+33">+33 (FR)</option>
                        <option value="+225">+225 (CI)</option>
                        <option value="+221">+221 (SN)</option>
                        <option value="+242">+242 (CG)</option>
                        <option value="+243">+243 (CD)</option>
                        <option value="+229">+229 (BJ)</option>
                        <option value="+228">+228 (TG)</option>
                        <option value="+241">+241 (GA)</option>
                        <option value="+235">+235 (TD)</option>
                        <option value="+226">+226 (BF)</option>
                        <option value="+212">+212 (MA)</option>
                        <option value="+213">+213 (DZ)</option>
                        <option value="+216">+216 (TN)</option>
                        <option value="+1">+1 (US/CA)</option>
                        <option value="+44">+44 (UK)</option>
                        <option value="+32">+32 (BE)</option>
                        <option value="+41">+41 (CH)</option>
                      </select>
                      <input
                        type="tel"
                        required
                        value={phoneLocal}
                        onChange={(e) => setPhoneLocal(e.target.value)}
                        className="flex-1 bg-secondary border border-border rounded-lg px-4 py-2.5 text-xs text-foreground focus:outline-none focus:border-primary"
                        placeholder="6xx xxx xxx"
                      />
                    </div>
                  </div>
                  <div>
                    <label className="text-xs font-semibold text-muted-foreground block mb-1">
                      {language === "fr" ? "Ville de résidence" : "City of residence"}
                    </label>
                    <select
                      value={formData.city}
                      onChange={(e) => setFormData({ ...formData, city: e.target.value })}
                      className="w-full bg-secondary border border-border rounded-lg px-4 py-2.5 text-xs text-foreground focus:outline-none focus:border-primary"
                    >
                      <option value="Douala">Douala</option>
                      <option value="Yaoundé">Yaoundé</option>
                      <option value="Autre">{language === "fr" ? "Autre" : "Other"}</option>
                    </select>
                  </div>
                </div>
                <div>
                  <label className="text-xs font-semibold text-muted-foreground block mb-1">
                    {language === "fr" ? "Rôle visé" : "Target role"}
                  </label>
                  <select
                    value={formData.type}
                    onChange={(e) => setFormData({ ...formData, type: e.target.value })}
                    className="w-full bg-secondary border border-border rounded-lg px-4 py-2.5 text-xs text-foreground focus:outline-none focus:border-primary"
                  >
                    <option value="Ambassadeur">
                      {language === "fr" ? "Ambassadeur (Recommandation)" : "Ambassador (Recommendation)"}
                    </option>
                    <option value="Conseiller Digital">
                      {language === "fr" ? "Conseiller Digital (Représentant)" : "Digital Advisor (Representative)"}
                    </option>
                    <option value="Closer Certifié">
                      {language === "fr" ? "Closer Certifié (Closer CRM)" : "Certified Closer (CRM Closer)"}
                    </option>
                  </select>
                </div>
                <div>
                  <label className="text-xs font-semibold text-muted-foreground block mb-1">
                    {language === "fr" ? "Motivation / Expérience (Facultatif)" : "Motivation / Experience (Optional)"}
                  </label>
                  <textarea
                    value={formData.experience}
                    onChange={(e) => setFormData({ ...formData, experience: e.target.value })}
                    className="w-full bg-secondary border border-border rounded-lg px-4 py-2.5 text-xs text-foreground focus:outline-none focus:border-primary h-20 resize-none"
                    placeholder={
                      language === "fr"
                        ? "Parlez-nous brièvement de votre parcours"
                        : "Tell us briefly about your background"
                    }
                  />
                </div>
                <button
                  type="submit"
                  className="w-full bg-primary text-primary-foreground py-3 rounded-lg font-bold text-xs flex items-center justify-center gap-2 hover:opacity-90 transition-opacity"
                >
                  {language === "fr" ? "Envoyer ma candidature" : "Submit my application"}
                </button>
              </form>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Partenaires;
