// This file is automatically generated. Do not edit it directly.
// (In practice this project does still hand-edit it when necessary — see
// SUPABASE_URL/KEY above, and the storage adapter below, added 2026-09-05.)
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { SupportedStorage } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ccrlfetratxnvgehiwnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_RPD3ekxLtXLZDrzLz_f3aA_2El2qnXd";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// "Rester connecté" (see the checkbox in src/pages/Auth.tsx): before this,
// `storage: localStorage` was hardcoded, so every session persisted across
// browser restarts no matter what the checkbox said — the checkbox only
// gated an unrelated "trusted device" flag used to auto-skip the login
// screen, so unchecking it never actually shortened anything real.
// This key, written by Auth.tsx right before signIn/signUp, decides where
// the Supabase SDK itself stores the session it is about to create:
// localStorage (checked — survives closing the browser, like Google's
// "stay signed in") or sessionStorage (unchecked — gone as soon as the
// tab/browser closes, so the next visit needs a fresh login). This is the
// real, standard mechanism behind a "remember me" checkbox; Supabase has no
// separate per-login token-lifetime knob to ask for instead.
export const REMEMBER_ME_KEY = "gln_remember_me";

const rememberAwareStorage: SupportedStorage = {
  getItem: (key) => localStorage.getItem(key) ?? sessionStorage.getItem(key),
  setItem: (key, value) => {
    if (localStorage.getItem(REMEMBER_ME_KEY) === "false") {
      sessionStorage.setItem(key, value);
      localStorage.removeItem(key);
    } else {
      localStorage.setItem(key, value);
      sessionStorage.removeItem(key);
    }
  },
  removeItem: (key) => {
    localStorage.removeItem(key);
    sessionStorage.removeItem(key);
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: rememberAwareStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
